package Form;


import Form.Form_Instruktur;
import Form.Form_Register_Member;
import Form.Form_Karyawan;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import transaksi.Form_Absensi;
import transaksi.Form_Pembayaran;
import transaksi.Form_Pemilihan_Instruktur;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Anditeguh
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Master = new javax.swing.JMenu();
        register_member = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        add_karyawan = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        Transaksi = new javax.swing.JMenu();
        pembayaran = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        absensi_member = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        laporan_data_member = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        laporan_data_karyawan = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        laporan_pembayaran = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        laporan_absensi = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        laporan_data_instruktur = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 118, 221));

        jLabel1.setFont(new java.awt.Font("Lato", 1, 70)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HELLO, SELAMAT DATANG ADMIN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addContainerGap(188, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(375, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(310, 310, 310))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 770));

        Master.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/leader.png"))); // NOI18N
        Master.setText("Master");
        Master.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        Master.setMargin(new java.awt.Insets(16, 16, 16, 16));
        Master.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasterActionPerformed(evt);
            }
        });

        register_member.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.META_MASK));
        register_member.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        register_member.setText("Registrasi Member");
        register_member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_memberActionPerformed(evt);
            }
        });
        Master.add(register_member);
        Master.add(jSeparator1);

        add_karyawan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.META_MASK));
        add_karyawan.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        add_karyawan.setText("Karyawan");
        add_karyawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_karyawanActionPerformed(evt);
            }
        });
        Master.add(add_karyawan);
        Master.add(jSeparator2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.META_MASK));
        jMenuItem3.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jMenuItem3.setText("Instruktur");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        Master.add(jMenuItem3);
        Master.add(jSeparator3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.META_MASK));
        jMenuItem4.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jMenuItem4.setText("Alat Gym");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        Master.add(jMenuItem4);

        jMenuBar1.add(Master);

        Transaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/tr.png"))); // NOI18N
        Transaksi.setText("Transaksi");
        Transaksi.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        Transaksi.setMargin(new java.awt.Insets(16, 16, 16, 16));

        pembayaran.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.META_MASK));
        pembayaran.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        pembayaran.setText("Pembayaran");
        pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembayaranActionPerformed(evt);
            }
        });
        Transaksi.add(pembayaran);
        Transaksi.add(jSeparator4);

        absensi_member.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.META_MASK));
        absensi_member.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        absensi_member.setText("Absensi Member");
        absensi_member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                absensi_memberActionPerformed(evt);
            }
        });
        Transaksi.add(absensi_member);
        Transaksi.add(jSeparator5);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.META_MASK));
        jMenuItem7.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        jMenuItem7.setText("Pemilihan Instruktur");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        Transaksi.add(jMenuItem7);

        jMenuBar1.add(Transaksi);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/report.png"))); // NOI18N
        jMenu3.setText("Report");
        jMenu3.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        jMenu3.setMargin(new java.awt.Insets(16, 16, 16, 16));

        laporan_data_member.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.META_MASK));
        laporan_data_member.setText("Laporan Data Member");
        laporan_data_member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporan_data_memberActionPerformed(evt);
            }
        });
        jMenu3.add(laporan_data_member);
        jMenu3.add(jSeparator6);

        laporan_data_karyawan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.META_MASK));
        laporan_data_karyawan.setText("Laporan Data Karyawan");
        laporan_data_karyawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporan_data_karyawanActionPerformed(evt);
            }
        });
        jMenu3.add(laporan_data_karyawan);
        jMenu3.add(jSeparator7);

        laporan_pembayaran.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.META_MASK));
        laporan_pembayaran.setText("Laporan Pembayaran");
        laporan_pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporan_pembayaranActionPerformed(evt);
            }
        });
        jMenu3.add(laporan_pembayaran);
        jMenu3.add(jSeparator8);

        laporan_absensi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.META_MASK));
        laporan_absensi.setText("Laporan Absensi");
        laporan_absensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporan_absensiActionPerformed(evt);
            }
        });
        jMenu3.add(laporan_absensi);
        jMenu3.add(jSeparator9);

        laporan_data_instruktur.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.META_MASK));
        laporan_data_instruktur.setText("Laporan Data Instruktur");
        laporan_data_instruktur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporan_data_instrukturActionPerformed(evt);
            }
        });
        jMenu3.add(laporan_data_instruktur);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png"))); // NOI18N
        jMenu4.setText("Logout");
        jMenu4.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        jMenu4.setMargin(new java.awt.Insets(16, 16, 16, 16));
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit.png"))); // NOI18N
        jMenu5.setText("Exit");
        jMenu5.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        jMenu5.setMargin(new java.awt.Insets(16, 16, 16, 16));
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void register_memberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_memberActionPerformed
        // TODO add your handling code here:
         new Form_Register_Member().setVisible(true);
    }//GEN-LAST:event_register_memberActionPerformed

    private void add_karyawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_karyawanActionPerformed
        // TODO add your handling code here:
         new Form_Karyawan().setVisible(true);
    }//GEN-LAST:event_add_karyawanActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
          new Form_Instruktur().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
          new Form_Alat_Gym().setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        new Form_Pemilihan_Instruktur().setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void absensi_memberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_absensi_memberActionPerformed
        // TODO add your handling code here:
        new Form_Absensi().setVisible(true);
    }//GEN-LAST:event_absensi_memberActionPerformed

    private void pembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembayaranActionPerformed
        // TODO add your handling code here:
        new Form_Pembayaran().setVisible(true);
    }//GEN-LAST:event_pembayaranActionPerformed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null,"Apakah Anda Yakin Logout ?", "select", JOptionPane.YES_NO_OPTION);
        if(a == 0){
            setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null,"Apakah Anda Yakin Exit ?", "select", JOptionPane.YES_NO_OPTION);
        if(a == 0){
           System.exit(0);
        }
        
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null,"Apakah Anda Yakin Exit ?", "select", JOptionPane.YES_NO_OPTION);
        if(a == 0){
           System.exit(0);
        }
    }//GEN-LAST:event_jMenu5MouseClicked

    private void laporan_data_memberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporan_data_memberActionPerformed
        // TODO add your handling code here:
        try {
             HashMap parameter = new HashMap();
             Class.forName("com.mysql.jdbc.Driver");
             Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:8889/gms","root","root");
             File file = new File("src/report/report_data_member.jasper");
             JasperReport jr = (JasperReport) JRLoader.loadObject(file);
             JasperPrint jp = JasperFillManager.fillReport(jr, parameter, conn);
             JasperViewer.viewReport(jp, false);
             JasperViewer.setDefaultLookAndFeelDecorated(true);
        } catch (Exception e) {
           javax.swing.JOptionPane.showMessageDialog(null,
                   "Data tidak dapat dicetak !!!"+"\n"+ e.getMessage(), "Cetak Data",
                   javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_laporan_data_memberActionPerformed

    private void laporan_data_karyawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporan_data_karyawanActionPerformed
        // TODO add your handling code here:
        try {
             HashMap parameter = new HashMap();
             Class.forName("com.mysql.jdbc.Driver");
             Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:8889/gms","root","root");
             File file = new File("src/report/report_data_karyawan.jasper");
             JasperReport jr = (JasperReport) JRLoader.loadObject(file);
             JasperPrint jp = JasperFillManager.fillReport(jr, parameter, conn);
             JasperViewer.viewReport(jp, false);
             JasperViewer.setDefaultLookAndFeelDecorated(true);
        } catch (Exception e) {
           javax.swing.JOptionPane.showMessageDialog(null,
                   "Data tidak dapat dicetak !!!"+"\n"+ e.getMessage(), "Cetak Data",
                   javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_laporan_data_karyawanActionPerformed

    private void laporan_data_instrukturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporan_data_instrukturActionPerformed
        // TODO add your handling code here:
           try {
             HashMap parameter = new HashMap();
             Class.forName("com.mysql.jdbc.Driver");
             Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:8889/gms","root","root");
             File file = new File("src/report/report_data_karyawan.jasper");
             JasperReport jr = (JasperReport) JRLoader.loadObject(file);
             JasperPrint jp = JasperFillManager.fillReport(jr, parameter, conn);
             JasperViewer.viewReport(jp, false);
             JasperViewer.setDefaultLookAndFeelDecorated(true);
        } catch (Exception e) {
           javax.swing.JOptionPane.showMessageDialog(null,
                   "Data tidak dapat dicetak !!!"+"\n"+ e.getMessage(), "Cetak Data",
                   javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_laporan_data_instrukturActionPerformed

    private void laporan_absensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporan_absensiActionPerformed
        // TODO add your handling code here:
        try {
             HashMap parameter = new HashMap();
             Class.forName("com.mysql.jdbc.Driver");
             Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:8889/gms","root","root");
             File file = new File("src/report/report_data_absensi.jasper");
             JasperReport jr = (JasperReport) JRLoader.loadObject(file);
             JasperPrint jp = JasperFillManager.fillReport(jr, parameter, conn);
             JasperViewer.viewReport(jp, false);
             JasperViewer.setDefaultLookAndFeelDecorated(true);
        } catch (Exception e) {
           javax.swing.JOptionPane.showMessageDialog(null,
                   "Data tidak dapat dicetak !!!"+"\n"+ e.getMessage(), "Cetak Data",
                   javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_laporan_absensiActionPerformed

    private void laporan_pembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporan_pembayaranActionPerformed
        // TODO add your handling code here:
          try {
             HashMap parameter = new HashMap();
             Class.forName("com.mysql.jdbc.Driver");
             Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:8889/gms","root","root");
             File file = new File("src/report/report_data_pembayaran.jasper");
             JasperReport jr = (JasperReport) JRLoader.loadObject(file);
             JasperPrint jp = JasperFillManager.fillReport(jr, parameter, conn);
             JasperViewer.viewReport(jp, false);
             JasperViewer.setDefaultLookAndFeelDecorated(true);
        } catch (Exception e) {
           javax.swing.JOptionPane.showMessageDialog(null,
                   "Data tidak dapat dicetak !!!"+"\n"+ e.getMessage(), "Cetak Data",
                   javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_laporan_pembayaranActionPerformed

    private void MasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasterActionPerformed
        // TODO add your handling code here:
          new Form_Alat_Gym().setVisible(true);
    }//GEN-LAST:event_MasterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Master;
    private javax.swing.JMenu Transaksi;
    private javax.swing.JMenuItem absensi_member;
    private javax.swing.JMenuItem add_karyawan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JMenuItem laporan_absensi;
    private javax.swing.JMenuItem laporan_data_instruktur;
    private javax.swing.JMenuItem laporan_data_karyawan;
    private javax.swing.JMenuItem laporan_data_member;
    private javax.swing.JMenuItem laporan_pembayaran;
    private javax.swing.JMenuItem pembayaran;
    private javax.swing.JMenuItem register_member;
    // End of variables declaration//GEN-END:variables
}
